### ISSUE TITLE
File "<stdin>", line 1 error

### ISSUE THREAD

**Issue by nick1001** [freeseek/getmyancestors#1]
Python 3.4.3 w/requests module. Here's my error...

```
root@d:/home/a/Downloads/getmyancestors-master# python3.4
Python 3.4.3 (default, Mar 23 2015, 12:32:24)
[GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> getmyancestors.py -a 4 -d 0 -u nickflyer -p *** -i LVF2-FVB -o out.ged
  File "<stdin>", line 1
    getmyancestors.py -a 4 -d 0 -u nickflyer -p *** -i LVF2-FVB -o out.ged
                         ^
SyntaxError: invalid syntax
>>>
```

Line 39:     # login (https://familysearch.org/developers/docs/guides/oauth1/login)
On that page, is says "Warning: OAuth 1.0 has been deprecated in favor of OAuth 2.0."
Maybe that's why?

**Comment by freeseek** [comment]
This is not how you run a python program.

Either you run it like this:
root@d:/home/a/Downloads/getmyancestors-master# python3.4 getmyancestors.py
-a 4 -d 0 -u nickflyer -p **\* -i LVF2-FVB -o out.ged

Or you run it like this:
root@d:/home/a/Downloads/getmyancestors-master# ./getmyancestors.py -a 4 -d
0 -u nickflyer -p **\* -i LVF2-FVB -o out.ged

You can use the -v flag to see what the program is doing while it is
running.

**Comment by nick1001** [comment]
Yes, my mistake. Thanks!
