### ISSUE TITLE
Needs updating to use OAuth2

### ISSUE THREAD

**Issue by OJFord** [freeseek/getmyancestors#2]
Really like the look of this! I hope you're still intending on maintaining it - unbelievably there seems to be no (other) lightweight way of exporting your tree.

Bizarre that FS don't give this option themselves. I could understand if it was "we don't want you using other tools" - but then they let third-party software do it.. weird.

Anyway, if you're no longer interested I _may_ get around to it myself... But I saw you link this repo in a couple places saying you'd be up for developing it if there's interest, so I guess I'm hoping that's still true :)

**Comment by freeseek** [comment]
I use the tool to sync the data from familysearch.org to ancestry.com and it has worked wonderfully for me. However, I can see other people might want further options implemented. If there is something in particular that you need, send an email to my personal email address and I will consider implementing it.

**Comment by OJFord** [comment]
Oh, it still works? It's silently failing for me, I assumed because FS had stopped supporting OAuth1. I'll take another look.

**Comment by freeseek** [comment]
I just tried it and it works for me. What error message do you get?

**Comment by OJFord** [comment]
You're quite right, it does work. I had some problem, and thinking maybe your key had expired/been deleted, generated my own which was a completely different format; so I concluded from the docs that they must now only accept oauth2..

Sorry about that - handy tool, thanks!
