### ISSUE TITLE
individual is not respected

### ISSUE THREAD

**Issue by Mika83AC** [freeseek/getmyancestors#6]
A gedcom file is successfull created, but the individual i entered in the pyhton script call is not respected. The gedcom file always containts the exact same content and individuals.

**Comment by Mika83AC** [comment]
UPDATE: this only happens to me, when i call the script multiple times (not parallel but successive) in the same terminal window. When i open a new terminal window and start a new run, the individual is respected.

Thx for your work :)

**Comment by freeseek** [comment]
What are the exact command line you used (excluding username and password) and the first few lines of the log?
