### ISSUE TITLE
No Issue - Positive feedback

### ISSUE THREAD

**Issue by tmathie** [freeseek/getmyancestors#7]
Hello, 
I just wanted to say that this tool is very handy. I a running 7 searches at the same time and have had no issues in the last 10. One has been running for over 46 hours, if i tried any of this in any other Genealogy software they would have all failed long ago. So, in short, Thank you

**Comment by freeseek** [comment]
The data in familysearch.org/tree is user contributed, so you deserve access to it in the most convenient way possible. However, I know that getmyancestors.py does not retrieve all that users have contributed. If you need any modifications please let me know. I would be happy to tweak the code to meet other users needs. Your feedback is much appreciated.
