### ISSUE TITLE
Direct Ancestors Request

### ISSUE THREAD

**Issue by tmathie** [freeseek/getmyancestors#8]
Good Day, 
This might be a pipe dream, but is it possible to only download Direct Ancestors?
Thank you, 
Torrey Mathie

**Comment by freeseek** [comment]
Do you mean without downloading uncles and aunts? That is one fix I have been procrastinating for a while. You have my word I will get around it at some point.

**Comment by tmathie** [comment]
Thank you, 
I had a DB of about a million individuals, i exported only direct ancestors and it knocked it down to 45,000. So i believe it would speed up the download process alot.

**Comment by freeseek** [comment]
I have cleaned up the code and now you can run the script so to only download direct ancestors (which now is the default behavior). I have also added a "-m" option which will download spouses of children and grandchildren (by default it will not). I have performed some minimal testing and it seems to work, but if you encounter any issues let me know.

**Comment by tmathie** [comment]
Great, 
Thank you, i will try it out and let you know if there are any problems.
